# # # # sol2
# The MIT License (MIT)
# 
# Copyright (c) 2013-2017 Rapptz, ThePhD, and contributors
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

sudo: required
language: cpp

git:
  depth: 5

services:
- docker

before_install:
- sudo apt install -y git

script:
- sudo docker image build --tag sol2:ci --build-arg "CI=${CI}" --build-arg "LUA_VERSION=${LUA_VERSION}" --build-arg "GCC_VERSION=${GCC_VERSION}" --build-arg "LLVM_VERSION=${LLVM_VERSION}" . 
- sudo docker run --name "sol2.test" --tty --env "CI=${CI}" --env "LUA_VERSION=${LUA_VERSION}" --env "GCC_VERSION=${GCC_VERSION}" --env "LLVM_VERSION=${LLVM_VERSION}" sol2:ci 
- sudo docker rm $(sudo docker ps -a -q)
- sudo docker rmi $(sudo docker image ls -q)

env:
    # GCC 4.9.x, 5.x, 6.x, 7.x
  - LUA_VERSION=5.3.4
    GCC_VERSION=4.9
    CI=true
  - LUA_VERSION=5.3.4
    GCC_VERSION=5
    CI=true
  - LUA_VERSION=5.3.4
    GCC_VERSION=6
    CI=true
  - LUA_VERSION=5.3.4
    GCC_VERSION=7
    CI=true
    # LLVM 3.6.x -> 5.0.x
  #- LUA_VERSION=5.3.4
  #  LLVM_VERSION=3.6.2
  #  CI=true
  #- LUA_VERSION=5.3.4
  #  LLVM_VERSION=3.7.1
  #  CI=true
  #- LUA_VERSION=5.3.4
  #  LLVM_VERSION=3.8.1
  #  CI=true
  #- LUA_VERSION=5.3.4
  #  LLVM_VERSION=3.9.0
  #  CI=true
  #- LUA_VERSION=5.3.4
  #  LLVM_VERSION=4.0.1
  #  CI=true
  #- LUA_VERSION=5.3.4
  #  LLVM_VERSION=5.0.1
  #  CI=true
    # Lua Versions 5.2.4, 5.1.5, and maybe LuaJIT (as well as x86)
  - LUA_VERSION=5.2.4
    GCC_VERSION=7
    CI=true
  - LUA_VERSION=5.1.5
    GCC_VERSION=7
    CI=true

matrix:
  fast_finish: true


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b864d553270a069d26c8
    on_success: change
    on_failure: always
    on_start: never
  email:
    on_success: change
    on_failure: change
    on_start: never
